// EDIT THIS MODULE TO DISPLAY HEX VALUES OF P, A, B
// A - HEX3, B - HEX2, P - HEX1, HEX0

//=======================================================
//  This code is generated by Terasic System Builder
//=======================================================

module hexdisplay(

	//////////// SEG7 //////////
	output		     [7:0]		HEX0,
	output		     [7:0]		HEX1,
	output		     [7:0]		HEX2,
	output		     [7:0]		HEX3,
	output		     [7:0]		HEX4,
	output		     [7:0]		HEX5,

	input 		     [7:0]		P,
	input				  [3:0]		A,
	input				  [3:0]		B
);



//=======================================================
//  REG/WIRE declarations
//=======================================================

	


//=======================================================
//  Structural coding
//=======================================================

	assign HEX5 = 7'b0000000;
	assign HEX4 = 7'b0000000;
	
	
endmodule
