
//=======================================================
//  This code is generated by Terasic System Builder
//=======================================================

module multiplication(

	//////////// SEG7 //////////
	output		     [7:0]		HEX0,
	output		     [7:0]		HEX1,
	output		     [7:0]		HEX2,
	output		     [7:0]		HEX3,
	output		     [7:0]		HEX4,
	output		     [7:0]		HEX5,

	//////////// KEY //////////
	input 		     [1:0]		KEY,

	//////////// LED //////////
	output		     [9:0]		LEDR,

	//////////// SW //////////
	input 		     [9:0]		SW,

	//////////// GPIO, GPIO connect to GPIO Default //////////
	inout 		    [35:0]		GPIO
);



//=======================================================
//  REG/WIRE declarations
//=======================================================

	wire [3:0] a, b;
	wire [7:0] p;
	wire [13:0] c;


//=======================================================
//  Structural coding
//=======================================================

	// INVENTORY
	// 16 ANDs, 12 FAs
	
	assign SW[7:4] = a;
	assign SW[3:0] = b;
	
	and (p[0], a[0], b[0]);
	and (c[0], a[1], b[0]);
	and (c[1], a[0], b[1]);
	and (c[

endmodule
