
//=======================================================
//  This code is generated by Terasic System Builder
//=======================================================

module ripplecarryadder(OV, s, a, b);

	output OV;
	output [3:0] s;
	input [3:0] a, b;


//=======================================================
//  REG/WIRE declarations
//=======================================================

	wire [3:0] a, b, s;
	wire [2:0] ci, c0;
	wire OV;


//=======================================================
//  Structural coding
//=======================================================	
	
	fulladder FA1 (c0[0], s[0], a[0], b[0], 1'b0);
	assign ci[0] = c0[0];
	fulladder FA2 (c0[1], s[1], a[1], b[1], ci[0]);
	assign ci[1] = c0[1];
	fulladder FA3 (c0[2], s[2], a[2], b[2], ci[1]);
	assign ci[2] = c0[2];
	fulladder FA4 (OV, s[3], a[3], b[3], ci[2]);

endmodule
